### ISSUE TITLE
I am getting this issue :(

### ISSUE THREAD

**Issue by skshadan** [litagin02/rvc-tts-webui#2]
2023-07-18 12:07:47 | INFO | faiss.loader | Loading faiss.
2023-07-18 12:07:47 | INFO | faiss.loader | Loading faiss.
Traceback (most recent call last):
  File "E:\KL2.0\rvc-tts\rvc-tts-webui\venv\lib\site-packages\faiss\loader.py", line 34, in <module>
    from .swigfaiss import *
  File "E:\KL2.0\rvc-tts\rvc-tts-webui\venv\lib\site-packages\faiss\swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: DLL load failed while importing _swigfaiss: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:/KL2.0/rvc-tts/rvc-tts-webui/app.py", line 22, in <module>
    from vc_infer_pipeline import VC
  File "e:\KL2.0\rvc-tts\rvc-tts-webui\vc_infer_pipeline.py", line 5, in <module>
    import pyworld, os, traceback, faiss, librosa, torchcrepe
  File "E:\KL2.0\rvc-tts\rvc-tts-webui\venv\lib\site-packages\faiss\__init__.py", line 17, in <module>
    from .loader import *
  File "E:\KL2.0\rvc-tts\rvc-tts-webui\venv\lib\site-packages\faiss\loader.py", line 39, in <module>
    from .swigfaiss import *
  File "E:\KL2.0\rvc-tts\rvc-tts-webui\venv\lib\site-packages\faiss\swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: DLL load failed while importing _swigfaiss: The specified module could not be found.

**Comment by skshadan** [comment]
one more

2023-07-18 12:35:07 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
2023-07-18 12:35:07 | INFO | faiss.loader | Loading faiss with AVX2 support.
2023-07-18 12:35:07 | INFO | faiss.loader | Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-07-18 12:35:07 | INFO | faiss.loader | Loading faiss.
2023-07-18 12:35:07 | INFO | faiss.loader | Successfully loaded faiss.
Found GPU NVIDIA GeForce RTX 3060
e:\KL2.0\rvc-tts\rvc-tts-webui\app.py:35: DeprecationWarning: There is no current event loop
  tts_voice_list = asyncio.get_event_loop().run_until_complete(edge_tts.list_voices())
Loading rmvpe model...
Traceback (most recent call last):
  File "e:\KL2.0\rvc-tts\rvc-tts-webui\app.py", line 46, in <module>
    rmvpe_model = RMVPE("rmvpe.py", config.is_half, config.device)
  File "e:\KL2.0\rvc-tts\rvc-tts-webui\rmvpe.py", line 334, in __init__
    ckpt = torch.load(model_path, map_location="cpu")
  File "E:\KL2.0\rvc-tts\rvc-tts-webui\venv\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "E:\KL2.0\rvc-tts\rvc-tts-webui\venv\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: could not find MARK

**Comment by litagin02** [comment]
In your first log, it seems that loading faiss was not successful (and I don't know why it occurred), but in your second log, faiss seems to be loaded successfully.
Do you obtain first log error now? or not happens anymore?

As for the second error, are you sure you downloaded `rmvpe.pt` (with about 172MB size)?
Maybe it's safe to download manually from
https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/rmvpe.pt
And check also for hubert_base.pt and also you can manually download it from
https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/hubert_base.pt
