### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by raze0727** [litagin02/rvc-tts-webui#3]
Traceback (most recent call last):   File "D:\Downloads\rvc-tts-webui-main\rvc-tts-webui-main\app.py", line 12, in <module>     from fairseq import checkpoint_utils   File "D:\Downloads\rvc-tts-webui-main\rvc-tts-webui-main\venv\Lib\site-packages\fairseq\__init__.py", line 20, in <module>     from fairseq.distributed import utils as distributed_utils   File "D:\Downloads\rvc-tts-webui-main\rvc-tts-webui-main\venv\Lib\site-packages\fairseq\distributed\__init__.py", line 7, in <module>     from .fully_sharded_data_parallel import (   File "D:\Downloads\rvc-tts-webui-main\rvc-tts-webui-main\venv\Lib\site-packages\fairseq\distributed\fully_sharded_data_parallel.py", line 10, in <module>     from fairseq.dataclass.configs import DistributedTrainingConfig   File "D:\Downloads\rvc-tts-webui-main\rvc-tts-webui-main\venv\Lib\site-packages\fairseq\dataclass\__init__.py", line 6, in <module>     from .configs import FairseqDataclass   File "D:\Downloads\rvc-tts-webui-main\rvc-tts-webui-main\venv\Lib\site-packages\fairseq\dataclass\configs.py", line 1104, in <module>     @dataclass      ^^^^^^^^^   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\dataclasses.py", line 1230, in dataclass     return wrap(cls)            ^^^^^^^^^   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\dataclasses.py", line 1220, in wrap     return _process_class(cls, init, repr, eq, order, unsafe_hash,            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\dataclasses.py", line 958, in _process_class     cls_fields.append(_get_field(cls, name, type, kw_only))                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\dataclasses.py", line 815, in _get_field     raise ValueError(f'mutable default {type(f.default)} for field ' ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory

**Comment by litagin02** [comment]
It seems that fairseq library does not support Python 3.10 currently:
https://github.com/facebookresearch/fairseq/issues/5012
So please use Python 3.10.

**Comment by AIhasArrived** [comment]
@raze0727 @litagin02 
 I have spent 3 entire weeks trying to find a way to clone correclty voices and I still did not get good results, I am so tired of it. I am contacting you because I saw you had old comments under old issues, you haev probably found better ways since then? Could you save me from my misery and direct me towards a method, a repo, a tutorial or anything that helps get to the point where I can actually clone a voice thats looks similar to the cloned voice please?  Help my soul lol. Really.
