### ISSUE TITLE
i dont know why  i need help

### ISSUE THREAD

**Issue by YesserFA** [litagin02/rvc-tts-webui#4]
2023-07-26 23:33:05 | INFO | faiss.loader | Loading faiss.
2023-07-26 23:33:05 | INFO | faiss.loader | Successfully loaded faiss.
Found GPU NVIDIA GeForce GT 1030
Loading hubert model...
Traceback (most recent call last):
  File "C:\Users\****\win\rvc-tts-webui\app.py", line 117, in <module>
    hubert_model = load_hubert()
  File "C:\Users\YFA_MFA\win\rvc-tts-webui\app.py", line 103, in load_hubert
    models, _, _ = checkpoint_utils.load_model_ensemble_and_task(
  File "C:\Users\****\win\rvc-tts-webui\venv\lib\site-packages\fairseq\checkpoint_utils.py", line 425, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "C:\Users\****\win\rvc-tts-webui\venv\lib\site-packages\fairseq\checkpoint_utils.py", line 315, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "C:\Users\****\win\rvc-tts-webui\venv\lib\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\****\win\rvc-tts-webui\venv\lib\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by litagin02** [comment]
Are you sure you downloaded `hubert_base.pt`?

**Comment by YesserFA** [comment]
> Are you sure you downloaded `hubert_base.pt`?

yes i download anythink

**Comment by litagin02** [comment]
Then sorry I don't know why this happens. Some google search says that this happens when the download is not complete. `hubert_base.pt` is about180MB size, and I suggest you download once more and try again.

**Comment by YesserFA** [comment]
> Then sorry I don't know why this happens. Some google search says that this happens when the download is not complete. `hubert_base.pt` is about180MB size, and I suggest you download once more and try again.

bruh 190 mb

**Comment by YesserFA** [comment]
ok i fixed thx @litagin02

**Comment by AIhasArrived** [comment]
@YesserFA 
 I have spent 3 entire weeks trying to find a way to clone correclty voices and I still did not get good results, I am so tired of it. I am contacting you because I saw you had old comments under old issues, you haev probably found better ways since then? Could you save me from my misery and direct me towards a method, a repo, a tutorial or anything that helps get to the point where I can actually clone a voice thats looks similar to the cloned voice please?  Help my soul lol. Really.
